### ISSUE TITLE
It can’t be found on quest

### ISSUE THREAD

**Issue by haxhaxhax526** [XavierSJC/pavlov-vr-quest-server#12]
I was looking and I made sure my info was right but I couldn’t find the server on quest

**Comment by XavierSJC** [comment]
Please give more details about your issue:

* Which command that you did do.
* Log of the Pavlov server

You can find the log file: /home/steam/pavlovserver/Pavlov/Saved/Logs/Pavlov.log
If you continue opening issues without these detail, I will block you.

**Comment by haxhaxhax526** [comment]
There is no directory there it didn’t create one

**Comment by XavierSJC** [comment]
I couldn't reproduce the issue with these details, closing.
