### ISSUE TITLE
ummm..... is there a menu for admins of the server?

### ISSUE THREAD

**Issue by YOURFUNGUY** [XavierSJC/pavlov-vr-quest-server#14]
is there?

**Comment by XavierSJC** [comment]
No, it doesn't.
To access an admin panel you need to use the RCON.

While configuring the container don't forget to use the parameters:
[-e RCON_PWD=<rcon_password>] [-e RCON_PORT=<rcon_port>]

To connect with RCON you can follow this steps:
http://wiki.pavlov-vr.com/index.php?title=Dedicated_server#Connecting_to_RCON

OR

You can use this site that provides a UI admin
https://pavlovrcon.com/
