### ISSUE TITLE
Can't figure out what to fill in the <tag> and <label> sections of the first command

### ISSUE THREAD

**Issue by Phantom387** [XavierSJC/pavlov-vr-quest-server#15]
I was trying to get the server to run on the shack rc, but couldn't. I found that skipping the first step, building it, makes the server run without rcon on the regular version of shack. Can you help with getting it to run properly?

Edit: The tag, 1.4.0 does nothing when I use it. Should I download the entire project and try again?

**Comment by XavierSJC** [comment]
## Run Shack RC Server

Yes, this README has the description only to execute the regular version of Shack, if you wish you can use my image for RC version that I created but I didn't document it in the README. The image is **powersjk/pavlov-vr-shack-rc-server**.

So to execute Shack RC, you can execute this command:
```
docker run -d --name pavlov-shack-rc-server -p 7000:7000/udp -p 7400:7400/udp -p 7777:7777 -p 7777:7777/udp -p 8177:8177 -p 8177:8177/udp -p 9100:9100 -e SERVER_NAME=Phanton387_Server -e RCON_PWD=MyRconPassword  -v pavlovRcData:/home/steam/pavlovserver/Pavlov/Saved powersjk/pavlov-vr-shack-rc-server:latest
```
Executing the command above a server version **SHACK_RC** with the name **Phanton387_Server** and password **MyRconPassword** will be created

## Customize your container
To build my image as is, you need to clone this repository and in the root folder execute:
```
docker build -t phanton387/pavlov-vr-shack:0.0.1 -f ./dockerfiles/Dockerfile .
```
After executing this build you have your own image docker to execute a server **SHACK LIVE** version


But this image will execute the regular shack, to change this you need to change line 13 at file [configfiles/install_pavlov.sh](https://github.com/XavierSJC/pavlov-vr-quest-server/blob/main/configfiles/install_pavlov.sh) to
```
~/Steam/steamcmd.sh +force_install_dir /home/steam/pavlovserver +login anonymous +app_update 622970 -beta shack_beta +exit
```
and execute the command `docker build` again, now you have your own image of the Shack RC version.


I will rewrite the README to explain better how to build this container and how to execute my images already created.
