### ISSUE TITLE
Unable to access RCON or change maps

### ISSUE THREAD

**Issue by xviper25** [XavierSJC/pavlov-vr-quest-server#2]
# Wrong group ownership of RCONSettings.txt & Game.ini
Took me a little while to figure out what the problem was so i thought i might aswell post a issue with the fix.
Mabye just clarify this in the readme.

Check ownership with:
ls -la 
![image](https://user-images.githubusercontent.com/17875118/149629133-05c1229a-f040-4672-a9da-2fec0a4bc492.png)

# To fix, edit Dockerfile and remove ".Template":
#Configuration and map list
COPY --chown=steam:steam ../configfiles/Game.ini ~~.template~~ /home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/

#Configure RCON
COPY --chown=steam:steam ../configfiles/RconSettings.txt ~~.template~~ /home/steam/pavlovserver/Pavlov/Saved/Config/

Great work btw. This repository really helped me get started with a server :) Thanks!

**Comment by XavierSJC** [comment]
Thank you for the feedback.
My previous intention was for the user to change the template file if more configuration is necessary, but I don't explain this in my readme file.

So I changed the file ConfigureServer.sh to edit the file Game.ini and RconSetting.txt. This way isn't necessary a template file and a reading of the Pavlov wiki the user can understand the configuration.
