### ISSUE TITLE
is there a tutorial I can find on YouTube because I need help to build this thing.

### ISSUE THREAD

**Issue by DefNotTiger** [XavierSJC/pavlov-vr-quest-server#5]

**Comment by XavierSJC** [comment]
Did you already read this [page](http://wiki.pavlov-vr.com/index.php?title=Dedicated_server)?
Can you give more details? What do you want? What is your issue?
Did you try to use the file docker-compose.yml? Just edit the environment variable SERVER_NAME.

In my tests you just need to:

1. Configure the ports.
2. Download the file docker-compose.yml
3. Edit the SERVER_NAME file
4. Execute `docker-compose up`

**Comment by Tigedraglon10** [comment]
> Did you already read this [page](http://wiki.pavlov-vr.com/index.php?title=Dedicated_server)? Can you give more details? What do you want? What is your issue? Did you try to use the file docker-compose.yml? Just edit the environment variable SERVER_NAME.
> 
> In my tests you just need to:
> 
> 1. Configure the ports.
> 2. Download the file docker-compose.yml
> 3. Edit the SERVER_NAME file
> 4. Execute `docker-compose up`

I'm trying to figure out how to use the docker command

**Comment by DefNotTiger** [comment]
Hello Xaiver, I'm here wondering how you can use the docker command, and thats all.

**Comment by DefNotTiger** [comment]
Okay, I'm saying where do you build the program/image to? because this is for oculus quest 2/ meta quest.

**Comment by XavierSJC** [comment]
[Docker](https://www.docker.com/) is a program to manage servers/applications, you will need to look for the basic concepts.

The image file is [dockerfiles/Dockerfile](https://github.com/XavierSJC/pavlov-vr-quest-server/blob/main/dockerfiles/Dockerfile), if you wish to build this image you can follow the steps:
```
git clone https://github.com/XavierSJC/pavlov-vr-quest-server.git
cd pavlov-vr-quest-server
docker build -t <tag>:<label> -f ./dockerfiles/Dockerfile .
```

This is a server to a game to Meta Quest hosted in an Ubuntu machine, so after you start your container you can play in your own server (install custom maps, put some password to only invite your friend, etc) through the game Pavlov in Meta Quest

**Comment by DefNotTiger** [comment]
oh my, Thanks for your support. thanks
