### ISSUE TITLE
Is there a specific tag and label I should use when I build this from dockerfile

### ISSUE THREAD

**Issue by haxhaxhax526** [XavierSJC/pavlov-vr-quest-server#7]
Hey just wondering if there is any specific info I need to write for the tag or label on the build command

**Comment by XavierSJC** [comment]
Yes, thank you for your warning, I just tested and the latest label is not working.

You can use this command to start your server:
`docker run -d --name pavlov-shack-server -p 7000:7000/udp -p 7400:7400/udp -p 7777:7777 -p 7777:7777/udp -p 8177:8177 -p 8177:8177/udp -p 9100:9100 -e SERVER_NAME=<your_server_name> -e [RCON_PWD=<rcon_password>] -e [RCON_PORT=<rcon_port>] -e [UPDATE_SERVER=True] -v pavlovData:/home/steam/pavlovserver/Pavlov/Saved powersjk/pavlov-vr-shack-server:1.2.0`

**Comment by XavierSJC** [comment]
The Docker Hub was updated, and the latest tag is working now.
