### ISSUE TITLE
Do I need Ubuntu 20.04 for this to run

### ISSUE THREAD

**Issue by haxhaxhax526** [XavierSJC/pavlov-vr-quest-server#8]
Just wondering if I need Ubuntu 20.04 specifically or if it works with any Linux distribution

**Comment by XavierSJC** [comment]
No, you don't

You need to install the Docker application, for this, you can follow this [page](https://docs.docker.com/desktop/install/linux-install/)

Configure your server to enable the follower ports:
* 7000
* 7400
* 7777
* 8177
* 9100

After the installation, just type this command:
`docker run -d --name pavlov-shack-server -p 7000:7000/udp -p 7400:7400/udp -p 7777:7777 -p 7777:7777/udp -p 8177:8177 -p 8177:8177/udp -p 9100:9100 -e SERVER_NAME=**haxhaxhax526_server** -e RCON_PWD=**9998** -v pavlovData:/home/steam/pavlovserver/Pavlov/Saved powersjk/pavlov-vr-shack-server:1.2.0`

OR

You can copy this [file ](https://github.com/XavierSJC/pavlov-vr-quest-server/blob/main/dockerfiles/docker-compose.yml) to your server, replace the fields as you wish. Pay attention to changing image label to "powersjk/pavlov-vr-shack-server:1.2.0" and execute the following command:
`docker-compose up -d`


After this exact command, a server is created with the name haxhaxhax526_server, you can check your server by this [link](https://pavlovhorde.com/) (Pay attention to select **Shark Servers**). You can even access your server using the password 9998.

**Comment by XavierSJC** [comment]
I identified that imaged storage in the label `latest` is failing. I will create the bug and fix it.

**Comment by haxhaxhax526** [comment]
Is the tag and label 
powersjk/pavlov-vr-shack-server:1.2.0

**Comment by XavierSJC** [comment]
Yes

**Comment by haxhaxhax526** [comment]
Will this work with kali pinux

**Comment by haxhaxhax526** [comment]
When I build the container with powersjk/pavlov-vr-shack-server:1.2.0 and Docker file It kicks an error: please use force_install_dir before logon

**Comment by XavierSJC** [comment]
Are you **building** with this tag? Why?
Please check this [answer](https://github.com/XavierSJC/pavlov-vr-quest-server/issues/5#issuecomment-1019294137) 

The build is running well, please can you be more specific? Attach some images maybe?
In my test, I could see a similar message but you only need to WAIT to complete the step.

**Comment by haxhaxhax526** [comment]
Now it’s working I’ll let you know if it sends any more errors

**Comment by haxhaxhax526** [comment]
Now it says: copy failed forbidden path outside the build context ../configfiles/Game.ini ()

**Comment by XavierSJC** [comment]
The tag is only necessary if you will download an **image** from a repository and start a **container**.
When you are building an image you are creating this with your own label/tag, which can be the same as mine.

The message is not an error, but a simple log, is your internet connection working well, as access to the Steam site? If you attach the complete message of your prompt I'm sure that I can help you more.

As well, please when you do any questions or describe possible issues, please write the exact line command that you did and the output of the message, or else the maintainer can't help you.

**Comment by XavierSJC** [comment]
> Now it says: copy failed forbidden path outside the build context ../configfiles/Game.ini ()

Please I need the command line and the complete messages or else I can't help you.

**Comment by haxhaxhax526** [comment]
I’m confused as to which command I need to use so I typed: sudo docker build -t powersjk/pavlov-vr-shack-server:1.2.0 -f ./dockerfiles/Dockerfile . After this command what do I type

**Comment by XavierSJC** [comment]
So you did:
`sudo docker build -t powersjk/pavlov-vr-shack-server:1.2.0 -f ./dockerfiles/Dockerfile .`

Now I need to the **COMPLETE** message, see what I wait you give me:
```
PS C:\repos\pavlov-vr-quest-server> docker build -t myrepository/pavlov:9.9.8 -f ./dockerfiles/Dockerfile .
[+] Building 67.6s (5/22)
 => [internal] load build definition from Dockerfile                                                                                                                                                        0.0s
 => => transferring dockerfile: 1.58kB                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                             0.0s
[+] Building 68.7s (5/22)
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 1.58kB                                                                            0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                   0.0s
[+] Building 264.9s (9/22)
 => [internal] load build definition from Dockerfile                                                                                                                          0.0s
 => => transferring dockerfile: 1.58kB                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                               0.0s
 => CACHED [ 1/18] FROM docker.io/library/ubuntu:20.04                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                             0.0s
 => => transferring context: 3.80kB                                                                                                                                           0.0s
 => [ 2/18] RUN apt update && apt install -y gdb curl wget nano lib32gcc1 libc++-dev unzip                                                                                  263.8s
 => [ 3/18] RUN useradd -m steam                                                                                                                                              0.5s
 => [ 4/18] COPY --chown=steam:steam ../configfiles/install_pavlov.sh ~                                                                                                       0.0s
 => ERROR [ 5/18] RUN ~/install_pavlov.sh                                                                                                                                     0.5s
------
 > [ 5/18] RUN ~/install_pavlov.sh:
#7 0.515 /bin/sh: 1: /home/steam/install_pavlov.sh: not found
------
executor failed running [/bin/sh -c ~/install_pavlov.sh]: exit code: 127
```

Again this doesn't look to me like any error...
Please always keep in mind:
* What I wanna do
* How I'm doing it
* What is gonna wrong (with more details possible, don't only one line)

Please try to rewrite your question keeping these three steps in mind

**Comment by haxhaxhax526** [comment]
The full line says: COPY —chown=steam:steam ../configfiles/Game.ini /home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/  copy failed forbidden path outside the build context ../configfiles/Game.ini ()

**Comment by haxhaxhax526** [comment]
Full log and command:  sudo docker build -t powersjk/pavlov-vr-shack-server:1.2.0 -f ./dockerfiles/Dockerfile .
Sending build context to Docker daemon  90.62kB
Step 1/30 : FROM ubuntu:20.04
 ---> d5447fc01ae6
Step 2/30 : LABEL maintainer "XavierSJC"
 ---> Using cache
 ---> a66456653c4d
Step 3/30 : ENV SERVER_NAME=charlies_server
 ---> Using cache
 ---> 7bea1ae78351
Step 4/30 : ENV RCON_PWD=hide-my-pass
 ---> Using cache
 ---> 58ba7305c3a3
Step 5/30 : ENV RCON_PORT=9100
 ---> Using cache
 ---> ced48c85bcb4
Step 6/30 : ENV UPDATE_SERVER=True
 ---> Using cache
 ---> a030549aa5a6
Step 7/30 : RUN apt update && apt install -y gdb curl wget nano lib32gcc1 libc++-dev unzip
 ---> Using cache
 ---> 1f00c21e6e05
Step 8/30 : RUN useradd -m steam
 ---> Using cache
 ---> 1547f6b96821
Step 9/30 : USER steam
 ---> Using cache
 ---> 4ef074b92bbf
Step 10/30 : RUN mkdir ~/Steam && cd ~/Steam && curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
 ---> Using cache
 ---> 70b49010264d
Step 11/30 : RUN ~/Steam/steamcmd.sh +login anonymous +force_install_dir /home/steam/pavlovserver +app_update 622970 -beta shack +exit
 ---> Using cache
 ---> 8fe61a2e118d
Step 12/30 : RUN ~/Steam/steamcmd.sh +login anonymous +app_update 1007 +quit
 ---> Using cache
 ---> 1e392f727816
Step 13/30 : RUN mkdir -p ~/.steam/sdk64
 ---> Using cache
 ---> e53ad02cf149
Step 14/30 : RUN cp ~/Steam/steamapps/common/Steamworks\ SDK\ Redist/linux64/steamclient.so ~/.steam/sdk64/steamclient.so
 ---> Using cache
 ---> da2096ba721f
Step 15/30 : RUN cp ~/Steam/steamapps/common/Steamworks\ SDK\ Redist/linux64/steamclient.so ~/pavlovserver/Pavlov/Binaries/Linux/steamclient.so
 ---> Using cache
 ---> dc66fef2c6e8
Step 16/30 : RUN chmod +x ~/pavlovserver/PavlovServer.sh
 ---> Using cache
 ---> eff30de94fd6
Step 17/30 : RUN mkdir -p /home/steam/pavlovserver/Pavlov/Saved/Logs
 ---> Using cache
 ---> 2dd3b12e4eba
Step 18/30 : RUN mkdir -p /home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer
 ---> Using cache
 ---> 4c8de845c303
Step 19/30 : RUN mkdir -p /home/steam/pavlovserver/Pavlov/Saved/maps
 ---> Using cache
 ---> ca94fa6543a5
Step 20/30 : RUN touch /home/steam/pavlovserver/Pavlov/Saved/Config/mods.txt
 ---> Using cache
 ---> 6729f380fd09
Step 21/30 : RUN touch /home/steam/pavlovserver/Pavlov/Saved/Config/blacklist.txt
 ---> Using cache
 ---> 8d70660d1e99
Step 22/30 : RUN touch /home/steam/pavlovserver/Pavlov/Saved/Config/whitelist.txt
 ---> Using cache
 ---> 2084b5963f6a
Step 23/30 : COPY --chown=steam:steam ../configfiles/Game.ini /home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/
COPY failed: forbidden path outside the build context: ../configfiles/Game.ini ()

**Comment by XavierSJC** [comment]
Did you clone my complete repository?
if you run an `ls -la` in the same path where you executed the command I expected to see these folders
* dockerfiles
* configfiles, with these files:
  * ConfigureServer.sh
  * Game.ini
  * install_pavlov.sh
  * RconSetting.txt
  * update_pavlov.sh

Again you need to explain to me what you wanna do.
Now I know What you did, what is wrong, but I'm sure that you don't will reach where you want. Explain me why you do it.

**Comment by haxhaxhax526** [comment]
Yes all those files are there and I just want to start the server so I can play pavlov

**Comment by XavierSJC** [comment]
> Yes all those files are there and I just want to start the server so I can play pavlov

Thank you, I can save a lot of your time! This image ups a server Pavlov, so I recommend you do this command:
`docker run -d --name pavlov-shack-server -p 7000:7000/udp -p 7400:7400/udp -p 7777:7777 -p 7777:7777/udp -p 8177:8177 -p 8177:8177/udp -p 9100:9100 -e SERVER_NAME=haxhaxhax526_server -e RCON_PWD=9998 -v pavlovData:/home/steam/pavlovserver/Pavlov/Saved powersjk/pavlov-vr-shack-server:1.2.0`

Don't forget to configure the right ports in your system. Using this command the server was created well, look at this image:
![image](https://user-images.githubusercontent.com/10137795/208222975-7f13356a-3e76-48b1-97ab-f886433cd386.png)



After you execute this command, you can open your game in your **Quest 2**, in the right side select "community server" and you can join your server with the name haxhaxhax526_server

**Comment by XavierSJC** [comment]
But this image is not a game, if you just wanna play Pavlov in your Quest, just install using this [link](https://www.oculus.com/experiences/quest/3649611198468269/?utm_source=sidequest)

**Comment by haxhaxhax526** [comment]
Will I be able to connect to the server from my quest

**Comment by XavierSJC** [comment]
Yes, you do.
Please try first, and ask later.

I will close this issue because your questions are about docker and don't have a relation to my image.
